FROM node:14.18.1
WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

COPY app/. .

RUN chown node:node ./
USER node
RUN npm ci

EXPOSE 8080

CMD npm start