---

plugins:
  - jest

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

env:
  node: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
